### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by alexandru-ghibea** [techwithtim/Flask-Web-App-Tutorial#105]
Seems that in the create_app() we need to set application context with app.app_context():

```
def create_database(app):
    if not path.exists('Website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')
```

**Comment by alexandru-ghibea** [comment]
But know, the database it's no longer being created

**Comment by Manish-KT** [comment]
Thanks for your help!

**Comment by alexandru-ghibea** [comment]
def create_database(app):
    if not path.exists('Website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')
