### ISSUE TITLE
delete notes has ceased to work

### ISSUE THREAD

**Issue by raj-bunsha** [techwithtim/Flask-Web-App-Tutorial#12]
delete not doesn't work now try changing it

**Comment by sravan-eng** [comment]
How can we do that ??

**Comment by Roshan057** [comment]
> delete not doesn't work now try changing it

yes me too...solved it?

**Comment by raj-bunsha** [comment]
Just see there I already posted the solution

**Comment by pvrvishal** [comment]
Instead Of Using javascript use this
`@views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return `redirect('/')``

**Comment by pvrvishal** [comment]
Instead Of javascript use this method

`@views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return redirect('/')`

**Comment by pvrvishal** [comment]
> @views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return redirect('/')

**Comment by pvrvishal** [comment]
Instead Of Using javascript use this.

> 
@views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return redirect('/')

**Comment by pvrvishal** [comment]
@views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return redirect('/')

**Comment by pvrvishal** [comment]
Instead Of Using Javascript use this.....

`

@views.route('/delete_note/<int:id>', methods=['POST'])
def delete_note(id):
    if request.method == 'POST':
        note = Note.query.get(id)
        print(note)
        db.session.delete(note)
        db.session.commit()
    return redirect('/')

`

**Comment by raj-bunsha** [comment]
yeah that's a good idea thanks for informing .I had no such idea then
