### ISSUE TITLE
Can't run main.py

### ISSUE THREAD

**Issue by SoxfnLj** [techwithtim/Flask-Web-App-Tutorial#149]
Im on the first step in this tutorial, and when I try to run the code, this error message appears, Traceback (most recent call last):
  File "c:\Users\LJH20\VSCode\Flask Web App\main.py", line 6, in <module>
    app.run(debug=True)

This is the code btw: 
main.py:
from website import create_app

app = create_app

if __name__ == '__main__':
    app.run(debug=True)
__init__.py: 
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'This is my Secret Key'

    return app

**Comment by drfq** [comment]
While in the main.py after completing the import the code needs to be changed from:

app = create_app =====> app = create_app()

The "()" is missing  and it is necessary in order to properly call the function that creates the app

**Comment by SoxfnLj** [comment]
OMG this works thank you so much!!

**Comment by KShireesha9505** [comment]
thank you, the issue got resolved

**Comment by KShireesha9505** [comment]
thank you
