### ISSUE TITLE
problems to start the server

### ISSUE THREAD

**Issue by Manuel9982** [techwithtim/Flask-Web-App-Tutorial#21]
Hello,
I have problems to start the server. 
I'm using Python 3.8.8 on Windows 10.
When I run the example on the Raspberry, it works flawlessly.

**main.py:**
`from website import create_app`
      `app = create_app()`
`if __name__ == '__main__':`
      `app.run(debug=True)`

**__init__.py:**
`from flask import Flask`
`def create_app():`
       `app = Flask(__name__)`
       ` return app`

**this is the result:**

runfile('Z:/Python/2021_07_15 Bsp Python Flask/Projektordner/main.py', wdir='Z:/Python/2021_07_15 Bsp Python Flask/Projektordner')
 * Serving Flask app "website" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with windowsapi reloader

I hope someone can help me. Thank you!

**Comment by zm0000001** [comment]
It looks like you have main.py located inside of /Projektordner so you should make main.py look like the following
`from Projektordner import create_app`
`app = create_app()`
`if __name__ == '__main__':`
`app.run(debug=True)`

**Comment by Manuel9982** [comment]
Thanks for the tip, unfortunately it does not work. This is my folder structure, I think it is correct. 
![Screenshot_1](https://user-images.githubusercontent.com/87522774/126025635-d576f8f5-82b8-4cbb-a8a0-fd576bfaac9e.jpg)

When I set debug to false I get this error message.
![grafik](https://user-images.githubusercontent.com/87522774/126025694-99684cec-34e5-499c-a7d5-be52147e0430.png)

**Comment by Manuel9982** [comment]
The problem is fixed, it was due to an "ü" in my PC name.

**Comment by zm0000001** [comment]
__pycache__ and database.db are created when the server runs, you do not have to do anything to those. Are you sure the server is not running? Can you send the entire output when debug=true and you try running the server?

**Comment by zm0000001** [comment]
> The problem is fixed, it was due to an "ü" in my PC name.

Awesome, glad you fixed it!
