### ISSUE TITLE
sqlalchemy.exc.IntegrityError

### ISSUE THREAD

**Issue by ktwitchn** [techwithtim/Flask-Web-App-Tutorial#24]
Seems like the issue is with db.session.commit()

Heres a screenshot of the error:

![Screen Shot 2021-08-31 at 9 54 35 PM](https://user-images.githubusercontent.com/89892238/131609225-0f501482-d814-44ba-9244-e8c946ba78d6.png)

My code looks right:

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('first_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) <2:
            flash('First Name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) <7:
            flash('Password must be at least 7 characters', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created', category='success')
            return redirect(url_for('views.home'))

**Comment by kaarn101** [comment]
Hey, I suggest you to check have you imported db  like  `  from . import db`  and also check indentation.

**Comment by ktwitchn** [comment]
I resolved the issue: 

For some reason I needed to put in a valid email, before I was just putting in "name@gmail.com" but it wouldn't run I guess it needed a valid email. Still haven't figured out why.
