### ISSUE TITLE
home.html trouble

### ISSUE THREAD

**Issue by Maverick-Shreeve** [techwithtim/Flask-Web-App-Tutorial#43]
![Screenshot 2022-02-25 214149](https://user-images.githubusercontent.com/99060319/155830908-e0d02d9e-5015-415c-b820-400e587c7033.jpg)
![Screenshot 2022-02-25 214213](https://user-images.githubusercontent.com/99060319/155830910-9823b746-be3c-4014-80d7-a66688888567.jpg)

I have everything else correct but I can not fix this problem inside of home.
does anyone know the solution?

**Comment by LA-Donnie** [comment]
What was the fix?
