### ISSUE TITLE
AttributeError: 'function' object has no attribute 'run'

### ISSUE THREAD

**Issue by uwugrim** [techwithtim/Flask-Web-App-Tutorial#46]
from website import create_app

app = create_app

if __name__ == '__main__':
    app.run(debug=True)

When I run main.py, I get this error "AttributeError: 'function' object has no attribute 'run'"

**Comment by prabhosle** [comment]
I am facing same problem . have you got solution ?

**Comment by bibinthomas123** [comment]
the ```create_app``` is a function  and in the if condition it is necessary to mention ``` __name__ == __main__```

the correct code is :
```py
from website import create_app


app = create_app()

if __name__ == '__main__' :

    app.run()
```
