### ISSUE TITLE
sqlite3.OperationalError) no such table: user

### ISSUE THREAD

**Issue by Ayellet221** [techwithtim/Flask-Web-App-Tutorial#56]
Hi Tim 
Thank you for the great tutorial
I am following the video and currently at 1:43:05. 
unfortunately I have an issue with the sigh-up option. i get this error message:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user

I made sure to import db as shown in the video and I don't know what else can be the problem. 
do you have any idea?

this is my code so far:

[auth.txt](https://github.com/techwithtim/Flask-Web-App-Tutorial/files/8642398/auth.txt)
[init.txt](https://github.com/techwithtim/Flask-Web-App-Tutorial/files/8642402/init.txt)
[models.txt](https://github.com/techwithtim/Flask-Web-App-Tutorial/files/8642403/models.txt)

**Comment by tommolittle** [comment]
have the same issue

**Comment by CyberCapivara** [comment]
Hi ! 
I was having the same issue, but I managed to "solve it" by deleting the database file at website folder and running the sign-up again.
I'm hoping that this does the job for you as well 
Cheers !

**Comment by Ayellet221** [comment]
It worked !
thank you
