### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by Gianlucca-Buzo** [techwithtim/Flask-Web-App-Tutorial#8]
Hi, I was doing the tutorial and had this error with the note's close button, It doesn't do anything. I clonned the repo and happens the same thing
![Captura de tela de 2021-02-24 14-59-25](https://user-images.githubusercontent.com/54315730/109044566-4ee74380-76b1-11eb-9a6f-ac9697a2d474.png)

**Comment by osborngh** [comment]
Pls did you use the same version of bootstrap Tim used?
I had a similar problem but later found out

**Comment by Gianlucca-Buzo** [comment]
When I pulled his last commit it worked out
