### ISSUE TITLE
Error with command: python main.py

### ISSUE THREAD

**Issue by mohamedmehdigara** [techwithtim/Flask-Web-App-Tutorial#99]
TypeError: SQLAlchemy.create_all() got an unexpected keyword argument 'app'

**Comment by Coolness448** [comment]
I have the same issue. I think it is to do with a sqlalchemy update.

**Comment by Coolness448** [comment]
> 

There is a solution here: https://github.com/techwithtim/Flask-Web-App-Tutorial/issues/82

def create_database(app):
if not path.exists('website/' + DB_NAME):
db.create_all(app=app)
print('Created Database!')

with this:

def create_database(app):
if not path.exists('website/' + DB_NAME):
with app.app_context():
db.create_all()
print('Created Database!')
